/*
 * Copyright 2010 UNAVCO, 6350 Nautilus Drive, Boulder, CO 80301
 * http://www.unavco.org
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or (at
 * your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser
 * General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation,
 * Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 * 
 */

package org.ramadda.util.grid;



/**
 * !!!!!!!!NOTE!!!!!!!
 * This file is copied from the UNAVCO SVN tree (I know I shouldn't do this
 * but I couldn't deal with yet another library from somewhere else).
 * SO: DO NOT EDIT THIS FILE HERE OR IF YOU DO MAKE SURE ITS CHECKED INTO 
 * THE UNAVCO TREE
 */
public class Grid {

    /** number of rows in grid */
    private int height;

    /** number of columns in grid */
    private int width;

    /** bounds */
    private double north;

    /** bounds */
    private double west;

    /** bounds */
    private double south;

    /** bounds */
    private double east;

    /** degrees width */
    private double gridWidth;

    /** degrees height */
    private double gridHeight;

    private double cellWidth;

    /** degrees height */
    private double cellHeight;

    private double cellWidth2;

    /** degrees height */
    private double cellHeight2;



    /**
     * ctor
     *
     * @param width number of columns
     * @param height number of rows
     * @param north northern bounds
     * @param west west bounds
     * @param south southern bounds
     * @param east east bounds
     */
    public Grid(int width, int height, double north, double west,
                double south, double east) {
        this.width      = width;
        this.height     = height;
        this.north      = north;
        this.west       = west;
        this.south      = south;
        this.east       = east;
        this.gridWidth  = east - west;
        this.gridHeight = north - south;
        cellWidth = gridWidth/width;
        cellHeight = gridHeight/height;
        cellWidth2 = cellWidth/2;
        cellHeight2 = cellHeight/2;
    }

    public String toString() {
        return north+" " + west +" " + south +" " + east;
    }

    /**
     * _more_
     *
     * @return _more_
     */
    public int getHeight() {
        return height;
    }

    /**
     * _more_
     *
     * @return _more_
     */
    public int getWidth() {
        return width;
    }

    /**
     * _more_
     *
     * @return _more_
     */
    public double getGridHeight() {
        return gridHeight;
    }

    /**
     * _more_
     *
     * @return _more_
     */
    public double getGridWidth() {
        return gridWidth;
    }

    /**
     *  Set the South property.
     *
     *  @param value The new value for South
     */
    public void setSouth(double value) {
        south = value;
    }

    /**
     *  Get the South property.
     *
     *  @return The South
     */
    public double getSouth() {
        return south;
    }

    /**
     *  Set the East property.
     *
     *  @param value The new value for East
     */
    public void setEast(double value) {
        east = value;
    }

    /**
     *  Get the East property.
     *
     *  @return The East
     */
    public double getEast() {
        return east;
    }

    /**
     *  Set the North property.
     *
     *  @param value The new value for North
     */
    public void setNorth(double value) {
        north = value;
    }

    /**
     *  Get the North property.
     *
     *  @return The North
     */
    public double getNorth() {
        return north;
    }

    public double getCellHeight() {
        return cellHeight;
    }

    public double getCellWidth() {
        return cellWidth;
    }



    /**
     *  Set the West property.
     *
     *  @param value The new value for West
     */
    public void setWest(double value) {
        west = value;
    }

    /**
     *  Get the West property.
     *
     *  @return The West
     */
    public double getWest() {
        return west;
    }



    /**
     * get the y index corresponding to the given latitude
     *
     * @param lat latitude
     *
     * @return y index
     */
    public int getLatitudeIndex(double lat) {
        if(lat>north) return 0;
        if(lat<south) return height-1;
        int idx = (int)((north-lat)/cellHeight);
        if(idx<0) idx=0;
        else if(idx>=height) idx=height-1;
        //        System.err.println("Lat:" + lat +" index:" + idx);
        return idx;
    }


    /**
     * get the x index corresponding to the given longitude
     *
     * @param lon longitude
     *
     * @return x index
     */
    public int getLongitudeIndex(double lon) {
        if(lon<west) return 0;
        if(lon>east) return width-1;
        int idx = (int)((lon-west)/cellWidth);
        if(idx<0) idx=0;
        else if(idx>=width) idx=width-1;
        //        System.err.println("Lon:" + lon +" index:" + idx);
        return idx;
    }

    public double getLatitude(int rowIndex) {
        //Offset to get the center
        return north-cellHeight2 - rowIndex*cellHeight;
    }

    public double getLongitude(int colIndex) {
        //Offset to get the center
        return west+cellWidth2 + colIndex*cellWidth;
    }



}
