/*
 * Copyright 2010 UNAVCO, 6350 Nautilus Drive, Boulder, CO 80301
 * http://www.unavco.org
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or (at
 * your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser
 * General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation,
 * Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 * 
 */

package org.ramadda.util.grid;


import ucar.unidata.ui.ImageUtils;
import ucar.unidata.util.IOUtil;

import ucar.unidata.util.StringUtil;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.*;

import java.io.File;

import java.util.List;



/**
 * !!!!!!!!NOTE!!!!!!!
 * This file is copied from the UNAVCO SVN tree (I know I shouldn't do this
 * but I couldn't deal with yet another library from somewhere else).
 * SO: DO NOT EDIT THIS FILE HERE OR IF YOU DO MAKE SURE ITS CHECKED INTO 
 * THE UNAVCO TREE
 *
 * @param <T>
 */
public class ObjectGrid<T> extends Grid {

    /** An extra 2d array of counts */
    private T[][] objectGrid;


    /**
     * ctor
     *
     * @param width number of columns
     * @param height number of rows
     * @param north northern bounds
     * @param west west bounds
     * @param south southern bounds
     * @param east east bounds
     */
    public ObjectGrid(int width, int height, double north, double west,
                      double south, double east) {
        super(width, height, north, west, south, east);
    }



    /**
     * create if needed and return the grid
     *
     * @return the grid
     */
    public T[][] getGrid() {
        if (objectGrid == null) {
            objectGrid = (T[][]) new Object[getHeight()][getWidth()];
        }
        return objectGrid;
    }


    public T getValue(double lat, double lon) {
        int yIndex = getLatitudeIndex(lat);
        int xIndex = getLongitudeIndex(lon);
        return getGrid()[yIndex][xIndex];
    }

    public T getValueFromIndex(int yIndex, int xIndex) {
        return getGrid()[yIndex][xIndex];
    }


    public void setValue(double lat, double lon, T value) {
        setValueByIndex(getLatitudeIndex(lat),  getLongitudeIndex(lon), value);
    }

    public void setValueByIndex(int yIndex, int xIndex, T value) {
        getGrid()[yIndex][xIndex] = value;
    }



    /**
     * _more_
     *
     * @param args _more_
     */
    public static void main(String[] args) {}

}
